name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-u-boot-nanopi-r4s:
    uses: ./.github/workflows/uboot_base_workflow.yml
    with:
      tgt: nanopi-r4s
      registry: ghcr.io

  create-release:
    runs-on: ubuntu-latest
    needs: [build-u-boot-nanopi-r4s]
    steps:
      - name: Download u-boot-nanopi-r4s release file
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 #v3.0.0
        with:
          name: u-boot-nanopi-r4s

      - name: Make nanopi-r4s release tarball
        run: tar cJf u-boot-nanopi-r4s.tar.xz ./u-boot-nanopi-r4s.bin

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 #v1
        with:
          files: ./u-boot-nanopi-r4s.tar.xz
