name: u-boot base workflow

on:
  workflow_call:
    inputs:
      tgt:
        required: true
        type: string
      registry:
        required: true
        type: string
        
jobs:
  build-uboot-bin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the u-boot bin
        run: cd u-boot-builder && docker buildx build . -f Dockerfile.u-boot-${{ inputs.tgt }} -o ./out

      - name: Upload the ${{ inputs.tgt }} u-boot
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.tgt }} u-boot
          path: u-boot-builder/out/u-boot-${{ inputs.tgt }}.bin