name: u-boot base workflow

on:
  workflow_call:
    inputs:
      tgt:
        required: true
        type: string
      registry:
        required: true
        type: string
        
jobs:
  build-uboot-bin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Don't copy qemu binary in github runner
        run: sed -i '/^COPY.*qemu-aarch64-static/d' u-boot-builder/Dockerfile.u-boot-${{ inputs.tgt }}

      - name: Build the u-boot bin
        run: cd u-boot-builder && docker buildx build . -f Dockerfile.u-boot-${{ inputs.tgt }} -o ./out

      - name: Upload the ${{ inputs.tgt }} u-boot
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 #v3.1.0
        with:
          name: u-boot-${{ inputs.tgt }}
          path: u-boot-builder/out/u-boot-${{ inputs.tgt }}.bin
          retention-days: 1